CIT-41 #time 3h improve the logicical code of blog app in the myWeb p…
codal-uchoudhary/python-training-2024 pull request #26
Opened 2024-02-16 13:18 UTC by codal-uchoudhary

…roject such as relation between modals and authentication

2024-02-18 05:12 UTC, arvish-codal commented on Projects/My_website/myWebsite/blog/views.py
>      iPost = Post.objects.all().get(slug = slug)
@codal-uchoudhary , are you sure this is the way we should be fetching an individual post instance?

2024-02-18 05:15 UTC, arvish-codal requested changes
@codal-uchoudhary  , are you sure this is the way we should be fetching an individual post instance as mentioned below ? 

>> Post.objects.all().get(slug=slug)

2024-02-19 06:21 UTC, codal-uchoudhary commented
for now it is working perfectly. but i will find some efficient way to fetch out post in the today's PR.

2024-02-19 06:47 UTC, arvish-codal commented
@codal-uchoudhary , why should be do all() if we want to fetch a unique Post ?? Why should we check each & every record.

can't we simply keep get(slug=slug) ?

2024-02-19 07:11 UTC, arvish-codal approved these changes

2024-02-19 07:11 UTC, merged